apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster-main
  namespace: dagster
spec:
  chart:
    spec:
      chart: dagster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nw-dagster
        namespace: flux-system
      version: 1.x.x
  interval: 1m0s
  values:
    flux:
      gitRepositories:
        main:
          url: ssh://git@github.com/LennartEversNW/KUB-CONFIG
          branch: main
          path: ./clusters/{{ .Values.global.clusterName }}
    global: {}
    monitoring:
      kdave:
        enabled: false